# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2024 J端rgen M端lbert <juergen.muelbert@outlook.de>
---
version: "0.2"
language: en  # Set a single default language

# Files to ignore
ignorePaths:
  - "**/node_modules"
  - "**/*.svg"
  - "**/*.qrc"
  - .git
  - .gitignore
  - .gitattributes
  - .vscode
  - .devcontainer
  - package-lock.json
  - pnpm-lock.yaml
  - cspell.config.yaml
  - project-words.txt # Exclude the word list itself
  - LICENSE
  - LICENSES/

# Files to check
files:
  - "**/*.md"
  - "**/*.markdown"
  - "**/*.adoc"
  - "**/*.asciidoc"
  - "**/*.htm"
  - "**/*.html"
  - "**/*.json"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.toml"

# Words to always ignore
words:
  - jmuelbert
  - J端rgen
  - M端lbert

# Words to flag as errors
flagWords:
  - hte
  - canot
  - cancelled

# CSpell behaviors
maxNumberOfProblems: 1000
useGitignore: true
allowCompoundWords: true
enableGlobDot: true
enableFiletypes:
  - shellscript
  - gitcommit

# Cache settings
cache:
  useCache: true
  cacheStrategy: content

# Overrides for specific files/globs
overrides:
  - filename: "**/*.de.md"
    language: en,de
  - filename: "**/*.es.md"
    language: en,es
  - filename: "**/*.it.md"
    language: en,it
  - filename: "**/*.py"
    language: en # Example for a Python file

# Project dictionary definitions
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true

# Use the project dictionary
dictionaries:
  - project-words

# Import language dictionaries
import:
  - "@cspell/dict-es-es"
  - "@cspell/dict-de-de"
  - "@cspell/dict-it-it"
