version = 1
SPDX-PackageName = "jm-python-template"
SPDX-PackageSupplier = "<juergen.muelbert@outlook.de>"
SPDX-PackageDownloadLocation = "https://www.github.com/jmuelbert/jm-python-template"

[[annotations]]
path = ["src/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "EUPL-1.2"


[[annotations]]
path = ["README.md", "AUTHORS.md", "CHANGELOG.md", "SECURITY.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = [".github/CODE_OF_CONDUCT.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "CC-BY-2.0 "

[[annotations]]
path = [".gitattributes", ".gitignore", ".markdown-link-check.json", ".markdownlint.json", ".npmrc", ".pre-commit-config.yaml", ".python-version"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["docs/**/**.md", "docs/**/**.html", "docs/**/**.css"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["docs/assets/**/**.png", "docs/assets/**/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "BSD-3-Clause"
