SPDX-PackageDownloadLocation = "https://www.github.com/jmuelbert/jm-python-template"
SPDX-PackageName             = "jm-python-template"
SPDX-PackageSupplier         = "<juergen.muelbert@outlook.de>"
version                      = 1

[[annotations]]
SPDX-FileCopyrightText  = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "EUPL-1.2"
path                    = [
"src/**",
"tests/**",
"package.json"
]
precedence              = "aggregate"


[[annotations]]
SPDX-FileCopyrightText  = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "CC-BY-2.0 "
path                    = ["README.md", "AUTHORS.md", "CHANGELOG.md", "SECURITY.md"]
precedence              = "aggregate"

[[annotations]]
SPDX-FileCopyrightText  = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "CC-BY-2.0 "
path                    = [
  ".github/CODE_OF_CONDUCT.md",
  ".github/CONTRIBUTING.md",
  ".github/PULL_REQUEST_TEMPLATE.md",
  ".github/styles/Microsoft/*",
  ".github/styles/Readability/*",
  ".github/styles/proselint/*",
  ]
precedence              = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "BSD-3-Clause"
path = [
  ".gitattributes",
  ".gitignore",
  ".github/branch-name-patterns.yml",
  ".github/gitleaks.toml",
  ".github/invite-contributors.yml",
  ".github/release-drafter.yml",
  ".github/repo-metadata.yml",
  ".github/badges/coverage.json",
  ".github/PULL_REQUEST_TEMPLATE.md",
  ".markdown-link-check.json",
  ".markdownlint.json",
  ".npmrc",
  ".readthedocs.yml",
  ".taplo.toml",
  ".pre-commit-config.yaml",
  ".python-version",
  ".vala.ini",
  ".vscode/*",
  "cspell.json",
  "project-words.txt"
]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText  = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path                    = ["docs/**/**.md", "docs/**/**.html", "docs/**/**.css"]
precedence              = "aggregate"

[[annotations]]
SPDX-FileCopyrightText  = "Jürgen Mülbert <juergen.muelbert@outlook.de>"
SPDX-License-Identifier = "BSD-3-Clause"
path                    = ["docs/assets/**/**.png", "docs/assets/**/**.svg"]
precedence              = "aggregate"
