---
# SPDX-License-Identifier: EUPL-1.2
# yamllint disable-line rule:line-length
# SPDX-FileCopyrightText: 2025-present Jürgen Mülbert <juergen.muelbert@outlook.de>

# https://taskfile.dev
# ------------------------
# Global Settings
# ------------------------
version: '3'

vars:
  LOG: 'warn'
  DOMAIN: 'jm-python-template'
  SRC_DIR: 'src'
  LOCALES_DIR: '{{.SRC_DIR}}/{{.DOMAIN}}/locales'
  GUI_DIR: '{{.SRC_DIR}}/{{.DOMAIN}}/gui'
  TRANSLATIONS_DIR: '{{.GUI_DIR}}/translations'
  LANGUAGES: 'en es fr de it pt pt_BR ru zh_CN zh_TW ja ko hi tr ar vi pl nl sv'

# ------------------------
# Tasks
# ------------------------
tasks:
  # ------------------------
  # Default
  # ------------------------
  default:
    desc: Lists available tasks
    cmds:
      - task --list

  # ------------------------
  # Environment
  # ------------------------
  sync:
    desc: Synchronizes dependencies and installs pre-commit hooks
    cmds:
      - uv sync {{.CLI_ARGS}}
      - pre-commit install

  rm:
    desc: Cleans up the project by removing generated files
    cmds:
      - |
        echo "🧹 Cleaning up project..."
        rm -rf dist htmlcov site .cache .ropeproject
        rm -rf .ruff_cache .pytest_cache .venv
        rm -f coverage.xml uv.lock
        rm -rf {{.LOCALES_DIR}}/*/LC_MESSAGES/*.mo
        rm -rf {{.LOCALES_DIR}}/*/LC_MESSAGES/*.po
        rm -rf {{.TRANSLATIONS_DIR}}/*.ts {{.TRANSLATIONS_DIR}}/*.qm
        rm -f {{.GUI_DIR}}/resources_rc.py
        hatch env prune || true

  # ------------------------
  # Tests & Coverage
  # ------------------------
  test:
    desc: Runs tests with a specific Hatch environment
    cmds:
      - hatch env create test
      - hatch run test:test {{.CLI_ARGS}}

  test-with-version:
    desc: Runs tests for a specific Python version
    cmds:
      - task: rm
      - hatch env create test
      - hatch run +py={{.VERSION}} test:test
    vars:
      VERSION: ''

  test-py:
    desc: Runs tests on multiple Python versions
    cmds:
      - task: test-with-version
        vars: {VERSION: 3.11}
      - task: test-with-version
        vars: {VERSION: 3.12}
      - task: test-with-version
        vars: {VERSION: 3.13}
      - task: rm

  coverage:
    desc: Runs code coverage tests
    cmds:
      - hatch env create test
      - hatch run test:coverage

  # ------------------------
  # Linting & Quality
  # ------------------------
  lint-python:
    desc: Runs all linting checks
    cmds:
      - hatch env create lint
      - hatch run lint:all

  spell-check:
    desc: Runs spell check
    cmds:
      - pnpm install
      - pnpm run lint:spell

  lint-docs:
    desc: Lints documentation files
    cmds:
      - pnpm install
      - pnpm run lint:prettier
      - pnpm run lint:markdown
      - pnpm run lint:links
      - pnpm run lint:spell

  lint-all:
    desc: All Lints
    cmds:
      - task: lint-python
      - task: lint-docs

  format-all:
    desc: Formats code
    cmds:
      - pnpm install
      - pnpm run format
      - hatch env create lint
      - hatch run lint:format

  pre-commit:
    desc: Runs pre-commit hooks
    cmds:
      - hatch env create lint
      - hatch run lint:precommit

  # ------------------------
  # Documentation
  # ------------------------
  serve:
    desc: Serves documentation locally
    cmds:
      - hatch env create docs
      - hatch run docs:serve

  docs-build:
    desc: Builds documentation
    cmds:
      - hatch env create docs
      - hatch run docs:build

  # ------------------------
  # Translations
  # ------------------------
  extract-qt-translations:
    desc: Extracts Qt translation strings
    cmds:
      # yamllint disable-line rule:line-length
      - ./scripts/extract_qt_translations.sh {{.LANGUAGES}} {{.TRANSLATIONS_DIR}} {{.GUI_DIR}}

  compile-qt-translations:
    desc: Compiles Qt translations
    cmds:
      # yamllint disable-line rule:line-length
      - ./scripts/compile_qt_translations.sh {{.LANGUAGES}} {{.TRANSLATIONS_DIR}} {{.GUI_DIR}}


  extract-babel-translations:
    desc: Extracts Babel translation strings
    cmds:
      # yamllint disable-line rule:line-length
      - ./scripts/compile_babel_translations.sh {{.SRC_DR}} {{.LOCALES_DIR}} {{.DOMAIN}}

  compile-babel-translations:
    desc: Updates and compiles Babel translations
    cmds:
      # yamllint disable-line rule:line-length
      - ./scripts/compile_babel_translations.sh {{.LANGUAGES}} {{.LOCALES_DIR}} {{.DOMAIN}}

  translate-qt:
    desc: Extracts and compiles Qt translations
    cmds:
      - task: extract-qt-translations
      - task: compile-qt-translations

  translate-babel:
    desc: Extracts and compiles Babel translations
    cmds:
      - task: extract-babel-translations
      - task: compile-babel-translations

  translate-all:
    desc: Extracts and compiles all translations
    cmds:
      - task: translate-qt
      - task: translate-babel
