---
# SPDX-License-Identifier: EUPL-1.2
# yamllint disable-line rule:line-length
# SPDX-FileCopyrightText: 2025-present Jürgen Mülbert <juergen.muelbert@outlook.de>

# Type Labels
type-fix:
  - any:
      - src/**/*.py
      - lib/**/*.py
      - "**/bugfix/**"
      - "**/hotfix/**"
      - "**/patch/**"

type-feature:
  - any:
      - src/**/*.py
      - lib/**/*.py
      - "**/feature/**"
      - "**/feat/**"
      - "**/enhancement/**"
type-docs:
  - any:
      - docs/**/*
      - "**/*.md"
      - "**/*.rst"
      - "**/*.txt"
      - mkdocs.yml
      - "**/*.ipynb"

type-test:
  - any:
      - tests/**/*.py
      - "**/test/**"
      - "**/tests/**"
      - "**/*_test.py"
      - "**/test_*.py"
      - "**/testing/**"
      - "**/*.spec.py"

type-chore:
  - any:
      - "**/build/**"
      - "**/ci/**"
      - "**/config/**"
      - "**/scripts/**"
      - .github/**/*
      - .editorconfig
      - .gitignore
      - .gitattributes
      - .markdown-link-check.json
      - .markdownlint.json
      - .prettierignore
      - .prettierrc.yaml
      - .taplo.toml
      - .yamllint
      - commitlint.config.js
      - cspell.json
      - cspell.config.yaml
      - .python-version
      - LICENSE*
      - LICENSES/*
      - NOTICE*
      - REUSE.toml

type-refactor:
  - any:
      - src/**/*.py
      - lib/**/*.py
      - "**/refactor/**"
      - "**/cleanup/**"

type-style:
  - any:
      - "**/*.css"
      - "**/*.scss"
      - "**/*.sass"
      - "**/*.less"
      - "**/*.html"
      - "**/*.jinja"
      - "**/*.j2"
      - .style.yapf
      - .pylintrc"
      - pyproject.toml
      - setup.cfg
      - .yamllint
      - .prettierrc.yaml

type-performance:
  - any:
      - src/**/*.py
      - lib/**/*.py
      - "**/perf/**"
      - "**/benchmark/**"
      - "**/optimizations/**"

# Status Labels
status/work-in-progress:
  - any:
      - "**/WIP/**"
      - "**/draft/**"

status/ready-for-review:
  - any:
      - "**/RFR/**"
      - "**/ready/**"

status/blocked:
  - any:
      - "**/blocked/**"
      - "**/hold/**"

status/needs-discussion:
  - any:
      - "**/discuss/**"
      - "**/proposal/**"
      - RFC.md

# Security Labels
security:
  - any:
      - src/security/**/*.py
      - "**/auth/**"
      - "**/oauth/**"
      - "**/crypto/**"
      - "**/password/**"
      - "**/permission/**"
      - "**/secret/**"
      - "**/*security*/**"
      - SECURITY.md

# Breaking Changes
breaking:
  - any:
      - "**/*.py"
      - "**/*.pyi"
      - "**/*.pyx"
      - "**/*.pxd"
      - docs/breaking-changes/**
      - docs/migrations/**
      - docs/upgrades/**

# Deprecation
deprecation:
  - any:
      - "**/*.py"
      - "**/*.pyi"
      - "**/*.pyx"
      - "**/*.pxd"
      - docs/deprecations/**

# CI/CD
ci:
  - any:
      - .github/workflows/**
      - .github/actions/**
      - .gitlab-ci.yml
      - azure-pipelines.yml
      - Jenkinsfile
      - .travis.yml
      - .circleci/**

# Dependencies
dependencies:
  - any:
      - requirements*.txt
      - requirements/**
      - poetry.lock
      - uv.lock
      - pyproject.toml
      - setup.py
      - setup.cfg
      - Pipfile*
      - conda-env.yml
      - .pre-commit-config.yaml
      - .python-version
      - package.json
      - package-lock.json
      - pnpm-lock.yaml

# Infrastructure
infrastructure:
  - any:
      - terraform/**
      - ansible/**
      - kubernetes/**
      - k8s/**
      - docker/**
      - Dockerfile*
      - docker-compose*.yml
      - helm/**
      - deployment/**
      - scripts/**
      - Taskfile.yml

# Documentation
documentation:
  - any:
      - docs/**/*
      - "**/*.md"
      - "**/*.rst"
      - "**/*.txt"
      - mkdocs.yml
      - "**/*.ipynb"
      - examples/**
      - samples/**
      - tutorials/**

# Testing
testing:
  - any:
      - tests/**
      - "**/test/**"
      - "**/tests/**"
      - "**/*_test.py"
      - "**/test_*.py"
      - pyproject.toml
      - pytest.ini
      - conftest.py
      - .coveragerc

# Database
database:
  - any:
      - "**/migrations/**"
      - "**/alembic/**"
      - "**/*model*.py"
      - "**/*schema*.py"
      - "**/db/**"

# API
api:
  - any:
      - "**/api/**"
      - "**/rest/**"
      - "**/graphql/**"
      - "**/endpoints/**"
      - "**/*controller*.py"
      - "**/*view*.py"

# UI/Frontend
frontend:
  - any:
      - "**/templates/**"
      - "**/static/**"
      - "**/assets/**"
      - "**/*.html"
      - "**/*.css"
      - "**/*.scss"
      - "**/*.js"

# Size Labels (handled by size-labeler action)
size/xs:
  - any: ["**/*"]
size/s:
  - any: ["**/*"]
size/m:
  - any: ["**/*"]
size/l:
  - any: ["**/*"]
size/xl:
  - any: ["**/*"]

# Priority
priority/critical:
  - any:
      - "**/hotfix/**"
      - "**/emergency/**"
      - "**/critical/**"

priority/high:
  - any:
      - "**/high-priority/**"
      - "**/important/**"

# Component Labels
component/core:
  - any:
      - src/core/**
      - lib/core/**
      - src/jm-python-template/core/**
      - lib/jm-python-template/core/**

component/utils:
  - any:
      - src/utils/**
      - lib/utils/**
      - src/jm-python-template/utils/**
      - lib/jm-python-template/utils/**

component/cli:
  - any:
      - src/cli/**
      - src/jm-python-template/cli/**
      - bin/**
      - scripts/**
