---
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2025-present Jürgen Mülbert <juergen.muelbert@outlook.de>

name: Python Environment Setup
description: Sets up a Python environment with Hatch.
inputs:
  python-version:
    description: Python version to use (e.g., 3.9, 3.x). Leave empty to use .python-version file.
    required: false
    # type: string
runs:
  using: composite
  steps:
    - name: 🐍 Set up Python (explicit version)
      if: inputs.python-version != ''
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: 🐍 Set up Python (from .python-version file)
      if: inputs.python-version == ''
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6.0.0
      with:
        python-version-file: .python-version
        cache: pip

    - name: Cache Hatch Dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809  # v4.2.4
      with:
        path: |
          ~/.cache/hatch
        key: ${{ runner.os }}-python-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Check Python Version (after setup)
      shell: bash
      run: python --version

    - name: 🔨 Set up Hatch
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade hatch
        hatch --version
